baseURL = 'https://hfx.bike/'
languageCode = 'en-us'
title = 'hfx.bike'
theme = "ananke"

[menu]
[[menu.main]]
name = "@BikeMayorHfx"
url = "https://twitter.com/BikeMayorHfx"
weight = 10
[[menu.main]]
name = "@BikeHfxStats"
url = "https://twitter.com/BikeHfxStats"
weight = 9
[[menu.main]]
name = "Kidical Mass"
url = "./kidical-mass/"
weight = 8

[params]
kidical_mass_email="KidicalMassHfx@gmail.com"
kidical_mass_twitter=""
kidical_mass_instagram=""
kidical_mass_facebook=""
